version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: vogelprompter/frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./public:/public
      - ./next.config.mjs:/next.config.mjs
      - ./package.json:/package.json
      - ./yarn.lock:/yarn.lock
      - ./tsconfig.json:/tsconfig.json
    ports:
      - "${FRONTEND_PORT}:3000"
