version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: vogelprompter/frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./teleprompter:/teleprompter
    ports:
      - "${FRONTEND_PORT}:3000"
